apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: mpragarok/multi-client
        resources:
          limits:
            # memory: "512Mi"
            # cpu: "500m"
            # deployment on GCP should use cpu 100M, memory 128 Mi
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
